### ISSUE TITLE
Etherpad Crash on save revision

### ISSUE THREAD

**Issue by 4censord** [ether/ep_git_commit_saved_revision#3]
# System info

On Archlinux with 
`uname -a Linux thearch 5.10.9-arch1-1 #1 SMP PREEMPT Tue, 19 Jan 2021 22:06:06 +0000 x86_64 GNU/Linux`
`node --version v15.6.0`
`npm --version 6.14.11`

**Client**
* Firefox
* Chromium

**etherpad-lite**
* Latest Release 1.8.7
* Latest develop ether/etherpad-lite@517fc88c5450370b425f7e6f25f408e270be0bbd

**ep_git_commit_saved_revision**
* version on npm `ep_git_commit_saved_revision@0.0.8`
* latest master 553faed1c62895b327a6809512bea2f053187847

# What happens
I open a new pad
I click `save revision`
I enter some text
I submit
Etherpad crashes

The relevant log section is:
```
[2021-01-21 14:58:24.650] [ERROR] console - DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ep_git_commit_saved_revision, function name: /home/daniel/projects/etherpad-lite/node_modules/ep_git_commit_saved_revision/handleMessage:handleMessage, hook: handleMessage): Attempt to resolve via returned value but it already resolved via callback. Ignoring this attempt to resolve.
[2021-01-21 14:58:35.315] [WARN] console - message {
  type: 'gitcommit',
  action: 'sendgitcommitMessage',
  message: 'Daniel',
  padId: 'Ig9LCClFvvXEC6tFyNVQ',
  myAuthorId: 'a.1cTcC2SEHlFIBRUY'
}
[2021-01-21 14:58:35.355] [ERROR] console - DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ep_git_commit_saved_revision, function name: /home/daniel/projects/etherpad-lite/node_modules/ep_git_commit_saved_revision/handleMessage:handleMessage, hook: handleMessage): Attempt to resolve via returned value but it already resolved via callback. Ignoring this attempt to resolve.
[2021-01-21 14:58:35.357] [ERROR] console - Error: DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ep_git_commit_saved_revision, function name: /home/daniel/projects/etherpad-lite/node_modules/ep_git_commit_saved_revision/handleMessage:handleMessage, hook: handleMessage): Attempt to resolve via returned value but it already resolved via callback. Ignoring this attempt to resolve.
    at settle (/home/daniel/projects/etherpad-lite/src/static/js/pluginfw/hooks.js:269:17)
    at /home/daniel/projects/etherpad-lite/src/static/js/pluginfw/hooks.js:326:18
```
as far as i have been able to understand the error is thrown in
`etherpad-lite/src/static/js/pluginfw/hooks.js:269:17`
```
259 | if (outcome != null) {
260 | 	// It was already settled, which indicates a bug.
261 | 	const action = err == null ? 'resolve' : 'reject';
262 | 	const msg = (`DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ${hook.part.plugin}, ` +
263 | 	             `function name: ${hook.hook_fn_name}, hook: ${hook.hook_name}): ` +
264 | 	             `Attempt to ${action} via ${how} but it already ${outcome.state} ` +
265 | 	             `via ${outcome.how}. Ignoring this attempt to ${action}.`);
266 | 	console.error(msg);
267 | 	if (state !== outcome.state || (err == null ? val !== outcome.val : err !== outcome.err)) {
268 | 	  // The second settle attempt differs from the first, which might indicate a serious bug.
269 | 	  throw new Error(msg);
270 | 	}
271 |   return;
272 | }
```

# Reproducing

get etherpad-lite
append settings.json with config. same as example but i changed the path
```
  "ep_git_commit_saved_revision":{
    "path":"/tmp/var/git",
    "initCommand":"git init ${path}",
    "saveCommand":"git -C \"${path}\" add \"${padId}.txt\" && git -C \"${path}\" commit -m \"${message}\""
  },
```
I also changed the loglevel to debug
`"loglevel": "DEBUG",`

run `npm install ep_git_commit_saved_revision`
run `./bin/debugRun.sh`

goto 0.0.0.0:9001
click _new pad_
click _save revision_
enter any text
click _submit_
Etherpad crashes

[debug.log](https://github.com/ether/ep_git_commit_saved_revision/files/5849842/debug.log)

**Comment by JohnMcLear** [comment]
Will fix ASAP.  Apologies.

**Comment by JohnMcLear** [comment]
Should be fixed now :)

**Comment by 4censord** [comment]
Thank you for your swift response.
